-- MySQL Script generated by MySQL Workbench
-- 01/19/17 22:58:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`producto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `producto` VARCHAR(45) NULL,
  `categoria` INT NULL,
  `precio_venta` DOUBLE NULL,
  `precio_compra` DOUBLE NULL,
  `eliminado` BIT(0) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`persona` ;

CREATE TABLE IF NOT EXISTS `mydb`.`persona` (
  `id_persona` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `documento_identificacion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `eliminado` BIT(0) NULL,
  `fecha_registro` DATETIME NULL,
  `fecha_nacimiento` DATETIME NULL,
  PRIMARY KEY (`id_persona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`compra_venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`compra_venta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`compra_venta` (
  `id_compra` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `valor` DOUBLE NULL,
  `id_persona` INT NOT NULL,
  `tipo` INT NULL COMMENT '1 para compra \n2 para venta',
  PRIMARY KEY (`id_compra`),
  INDEX `fk_compra_persona_idx` (`id_persona` ASC),
  CONSTRAINT `fk_compra_persona`
    FOREIGN KEY (`id_persona`)
    REFERENCES `mydb`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inventario_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`inventario_producto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`inventario_producto` (
  `id_inventario_producto` INT NOT NULL AUTO_INCREMENT,
  `id_compra` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `fecha` DATETIME NULL,
  `cantidad_producto` VARCHAR(45) NULL,
  PRIMARY KEY (`id_inventario_producto`),
  INDEX `fk_inventario_producto_compra1_idx` (`id_compra` ASC),
  INDEX `fk_inventario_producto_producto1_idx` (`id_producto` ASC),
  CONSTRAINT `fk_inventario_producto_compra1`
    FOREIGN KEY (`id_compra`)
    REFERENCES `mydb`.`compra_venta` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventario_producto_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
